server:
  port: 8080

spring:
  application:
    name: recipease
  
  datasource:
    driverClassName: org.postgresql.Driver
    initilization-mode: never
    password: 123
    username: abc
    url: jdbc:postgresql://34.70.51.191:5432/recipease
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: recipease
    show-sql: false
